### ISSUE TITLE
Lollipop patches don't apply

### ISSUE THREAD

**Issue by gibsson** [NXPNFCLinux/android_nxp-nci#1]
Please specify the exact Lollipop version it has been tested against.

Clearly it was a version >= 5.1.0 as patches fail on 5.0.0_r2.

As an example, your linker.cpp bionic file requires UniquePtr.h which didn't appear in AOSP before 5.1.0_r1:
http://androidxref.com/5.0.0_r2/search?q=&defs=&refs=&path=UniquePtr.h&hist=&project=bionic
http://androidxref.com/5.1.0_r1/search?q=&defs=&refs=&path=UniquePtr.h&hist=&project=bionic

**Comment by jgeslin** [comment]
The version used as basis is android-5.1.1_r3.

**Comment by gibsson** [comment]
So would you have a solution for 5.0.0 users? I've basically got everything merged but the NfcNci application can't build as the BeamManager doesn't exist in 5.0.0.

**Comment by jgeslin** [comment]
Indeed, hard merge of files induced such issues.
May I ask you to try NXP-NCI inclusion to 5.0.0 using patches (https://nxp.box.com/NXP-LollipopPackage) and feedback ?

**Comment by gibsson** [comment]
I've only tried the Nfc app but it still doesn't apply, for instance it tries to patch BeamSendService.java which doesn't exist in our android-5.0.2_r1 tag.
http://androidxref.com/5.1.0_r1/search?q=&defs=&refs=&path=BeamSendService.java&hist=&project=packages
http://androidxref.com/5.0.0_r2/search?q=&defs=&refs=&path=BeamSendService.java&hist=&project=packages

Do you have anything older than that?

**Comment by jgeslin** [comment]
Please give it a try with this specific package: https://nxp.box.com/NXPNCI-Lollipop-5-0

**Comment by gibsson** [comment]
This last package built just fine. Thank you so much for your support!
