### ISSUE TITLE
NFC not working at bootup

### ISSUE THREAD

**Issue by gibsson** [NXPNFCLinux/android_nxp-nci#2]
Hi,

After integrating all the components from this repo (or more exactly the 5.0.0 version), NFC is working fine except at bootup.

Indeed, when booting up, the NFC option is ON just fine but nothing happens when a tag brought close to the antenna. Then by turning the NFC off and on again in the Settings menu, everything is back to normal and the tag will be read properly.

Has anyone experienced the same issue?

Here is a logcat and dmesg output which hopefully will help explain this behaviour:
http://pastebin.com/WkHYeE57

Thanks,
Gary

**Comment by jgeslin** [comment]
Could you provide a logcat of the only first part (before going to the setting menu) ?

**Comment by gibsson** [comment]
The logcat provided is the one before going to the Settings.

**Comment by jgeslin** [comment]
From the log, everything went well (discovery was properly started) ... but just at the end (just after the discovery has been started) the discovery is being stopped:
     1610: D/BrcmNfcJni(  808): nfcManager_disableDiscovery: enter;

Looks someone stops the discovery (can be automatic discovery stop in case of screen off or lock). Please provide full log (without any filter) to see if we can identified the process stopping the discovery.

**Comment by gibsson** [comment]
Here is the full log without going to the Settings Menu: http://pastebin.com/iw685wMC
Issue seems to be:
E/NfcService(  800): applyRouting -2

**Comment by jgeslin** [comment]
This seems for me related to a wrong management of the SCREEN state. See NfcService.java !

**Comment by gibsson** [comment]
Well I agree the there a filter on SCREEN state changes but the last one we see is a SCREEN_ON Intent:
D/BrcmNfcJni(  805): SetScreenState: enter
D/BrcmNfcJni(  805): Screen ON-Unlocked
D/BrcmNfcJni(  805): SetScreenState: Success NFA_SendNxpNciCommand

What makes you think this is the issue?

**Comment by gibsson** [comment]
Ok I've found the issue, fixed it, and then realized that you guys also fixed it in the 5.1.1 source code... This issue only occurs on the 5.0.0 source code you provided then. It is due to USER_PRESENT intent being sent after the screen is already ON_UNLOCKED:
https://github.com/NXPNFCLinux/android_nxp-nci/blob/master/aosp/packages/apps/Nfc/src/com/android/nfc/NfcService.java#L4772

In the 5.0.0 source code, when USER_PRESENT is received with an ON screen it ends up applying SCREEN_STATE_OFF as it is the default value...

**Comment by gibsson** [comment]
Thanks for your help!
